# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - totdemoeric

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://totmattdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4e7227dfabc64e339edd4f06ae3288f1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f2037f4d8a014e33a0e750a3a0ea3db5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: totmattdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e7227dfabc64e339edd4f06ae3288f1 }}/totmattdemo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'totdemoeric'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b1a9ae76979f4bc2a04ae5bf7eaf8c28 }}
        images: 'totmattdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e7227dfabc64e339edd4f06ae3288f1 }}/totmattdemo:${{ github.sha }}'