# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - totmattdemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://totmattdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f94e0d5aa2cc4017b7539690aed0b11d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7d24c20e63034c54ba03145af0867649 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: totmattdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f94e0d5aa2cc4017b7539690aed0b11d }}/matt_demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'totmattdemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7571a5cdfd12421e9aaa98eafbd05e34 }}
        images: 'totmattdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f94e0d5aa2cc4017b7539690aed0b11d }}/matt_demo:${{ github.sha }}'